/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program.admin;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fattahul_Akbar
 */
public class DataBobot extends javax.swing.JFrame {
    
    DefaultTableModel tblBobot;

    koneksi conn= new koneksi();

    /**
     * Creates new form DataBobot
     */
    public DataBobot() {
        initComponents();
         setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(this);
        tampilBobot();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        btn_simpan = new javax.swing.JButton();
        txt_b4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_b3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_b2 = new javax.swing.JTextField();
        txt_b1 = new javax.swing.JTextField();
        btn_hapus = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_bobot = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("DATA BOBOT");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(357, 11, 109, 21);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(10, 38, 820, 10);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        txt_b4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_b4KeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Bakat");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Minat");

        txt_b3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_b3KeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Dukungan Orang tua");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Perestasi");

        txt_b2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_b2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_b2KeyTyped(evt);
            }
        });

        txt_b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_b1ActionPerformed(evt);
            }
        });

        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/del.jpg"))); // NOI18N
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btn_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_b2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_b1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_b3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_b4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(213, 213, 213))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_b3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_b4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(120, 60, 550, 270);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setText("DAFTAR BOBOT");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(347, 355, 131, 21);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(0, 382, 830, 10);

        tbl_bobot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_bobot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_bobotMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_bobot);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(140, 440, 510, 264);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pngwing.com (1).png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 330, 700, 540);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pngwing.com (1).png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 70, 730, 340);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logooo.jpg"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 50, 90, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logooo.jpg"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 394, 100, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed

    if (!txt_b1.isEnabled() && !txt_b2.isEnabled() && !txt_b3.isEnabled() && !txt_b4.isEnabled()) {
        JOptionPane.showMessageDialog(null, "Bobot sudah terisi dan maksimal 1. Tidak dapat menyimpan data baru.");
        return; 
    }

    String sql = "INSERT INTO tbl_bobot (b1, b2, b3, b4) VALUES (?, ?, ?, ?)";
    try {
        PreparedStatement stat = conn.getconnetion().prepareStatement(sql);
        stat.setString(1, txt_b1.getText());
        stat.setString(2, txt_b2.getText());
        stat.setString(3, txt_b3.getText());
        stat.setString(4, txt_b4.getText());
        stat.executeUpdate();
        
        JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        clear();
        tampilBobot();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Data gagal disimpan " + e);
    }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void txt_b4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_b4KeyTyped
        
    }//GEN-LAST:event_txt_b4KeyTyped

    private void txt_b3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_b3KeyTyped
        
    }//GEN-LAST:event_txt_b3KeyTyped

    private void txt_b2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_b2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_b2KeyReleased

    private void txt_b2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_b2KeyTyped
        
    }//GEN-LAST:event_txt_b2KeyTyped

    private void txt_b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_b1ActionPerformed

    private void tbl_bobotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bobotMouseClicked
  
    int row = tbl_bobot.getSelectedRow();

    
    if (row >= 0) {
        // Ambil nilai dari tabel dan set ke JTextField
        txt_b1.setText(tbl_bobot.getValueAt(row, 0).toString());
        txt_b2.setText(tbl_bobot.getValueAt(row, 1).toString());
        txt_b3.setText(tbl_bobot.getValueAt(row, 2).toString());
        txt_b4.setText(tbl_bobot.getValueAt(row, 3).toString());
        
        // Nonaktifkan JTextField karena data sudah ada
        txt_b1.setEnabled(false);
        txt_b2.setEnabled(false);
        txt_b3.setEnabled(false);
        txt_b4.setEnabled(false);
    }
    }//GEN-LAST:event_tbl_bobotMouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
       
     try {
        
        String sqlDelete = "DELETE FROM tbl_bobot";
        PreparedStatement statDelete = conn.getconnetion().prepareStatement(sqlDelete);
        statDelete.executeUpdate();
        
        JOptionPane.showMessageDialog(null, "Data berhasil dihapus");

        clear();
         normal();
        DefaultTableModel model = (DefaultTableModel) tbl_bobot.getModel();
        model.setRowCount(0); 
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Data gagal dihapus " + ex);
    }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void clear(){
        txt_b1.setText("");
        txt_b2.setText((""));
        txt_b3.setText("");
        txt_b4.setText("");
    }
    
    private void normal(){
    txt_b1.setEnabled(true);
    txt_b2.setEnabled(true);
    txt_b3.setEnabled(true);
    txt_b4.setEnabled(true);
    }
    
    public void tampilBobot() {
    tblBobot = new DefaultTableModel();
    tblBobot.addColumn("Minat");
    tblBobot.addColumn("Bakat");
    tblBobot.addColumn("Prestasi");
    tblBobot.addColumn("Dukungan Orang Tua");
    tbl_bobot.setModel(tblBobot);
    
    try {
        ResultSet res = conn.ambilData("SELECT * FROM tbl_bobot");
        if (res.next()) {
            
            txt_b1.setEnabled(false);
            txt_b2.setEnabled(false);
            txt_b3.setEnabled(false);
            txt_b4.setEnabled(false);
            
            tblBobot.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4)});
        } else {
            txt_b1.setEnabled(true);
            txt_b2.setEnabled(true);
            txt_b3.setEnabled(true);
            txt_b4.setEnabled(true);
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, ex);
    }
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataBobot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataBobot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataBobot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataBobot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataBobot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tbl_bobot;
    private javax.swing.JTextField txt_b1;
    private javax.swing.JTextField txt_b2;
    private javax.swing.JTextField txt_b3;
    private javax.swing.JTextField txt_b4;
    // End of variables declaration//GEN-END:variables
}
